### PR TITLE
fix(typescript-eslint): address trailing path sep bug in `tsconfigRootDir` inference

### LINKED ISSUE #11398: Bug: Inferred parserOptions.tsconfigRootDir concatenates incorrectly when a space is present in the path
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I believe this issue may have something to do with: https://github.com/typescript-eslint/typescript-eslint/pull/11370

This was working in version 8.36.0

[This is the line that I think is breaking things](https://github.com/matthew-plusprogramming/monorepo/blob/87e1108582163aeb91700ba86729f13f6b68cd3d/src/packages/eslint-config/index.ts#L40)

Here is my stacktrace:
```
npm run lint

> monorepo@0.0.1 lint
> turbo run lint

turbo 2.5.4

• Packages in scope: @configs/eslint-config, @configs/ts-config, @configs/vite-config, @utils/type-utils, monorepo-cdk, node-server
• Running lint in 6 packages
• Remote caching disabled
monorepo-cdk:lint: cache miss, executing c976c864fcf47ec0
node-server:lint: cache miss, executing cf188dbd4300770e
monorepo-cdk:lint: 
node-server:lint: 
node-server:lint: 
node-server:lint: > node-server@0.0.1 lint
node-server:lint: > eslint src
node-server:lint: 
monorepo-cdk:lint: 
monorepo-cdk:lint: > monorepo-cdk@0.0.1 lint
monorepo-cdk:lint: > eslint src
monorepo-cdk:lint: 

node-server:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server/src/index.ts
node-server:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/apps/node-server/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server/Projects/monorepo/src/apps/node-server/tsconfig.json'
node-server:lint: 
node-server:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server/src/vite-env.d.ts
node-server:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/apps/node-server/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server/Projects/monorepo/src/apps/node-server/tsconfig.json'
node-server:lint: 
node-server:lint: ✖ 2 problems (2 errors, 0 warnings)
node-server:lint: 

monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/constants/backend.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/index.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/stacks.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/stacks/bootstrap/index.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/stacks/my-stack/index.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/types/stack.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/src/utils/standard-backend.ts
monorepo-cdk:lint:   0:0  error  Parsing error: error TS5012: Cannot read file 'Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json': ENOENT: no such file or directory, open '/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk/Projects/monorepo/src/cdk/monorepo-cdk/tsconfig.json'
monorepo-cdk:lint: 
monorepo-cdk:lint: ✖ 7 problems (7 errors, 0 warnings)
monorepo-cdk:lint: 
npm error Lifecycle script `lint` failed with error:
npm error code 1
npm error path /Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server
npm error Lifecycle script `lint` failed with error:
npm error workspace node-server@0.0.1
npm error location /Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server
npm error command failed
npm error command sh -c eslint src
npm error code 1
npm error path /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk
npm error workspace monorepo-cdk@0.0.1
npm error location /Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk
npm error command failed
npm error command sh -c eslint src


monorepo-cdk:lint: ERROR: command finished with error: command (/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk) /Users/matthewlin/.nvm/versions/node/v22.14.0/bin/npm run lint exited (1)
node-server:lint: ERROR: command finished with error: command (/Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server) /Users/matthewlin/.nvm/versions/node/v22.14.0/bin/npm run lint exited (1)
monorepo-cdk#lint: command (/Users/matthewlin/Desktop/Personal Projects/monorepo/src/cdk/monorepo-cdk) /Users/matthewlin/.nvm/versions/node/v22.14.0/bin/npm run lint exited (1)
node-server#lint: command (/Users/matthewlin/Desktop/Personal Projects/monorepo/src/apps/node-server) /Users/matthewlin/.nvm/versions/node/v22.14.0/bin/npm run lint exited (1)
```
My 

### Reproduction Repository Link

https://github.com/matthew-plusprogramming/monorepo/tree/broken-version/packages/eslint-config

### Repro Steps

1) clone the repo
2) Switch to the `broken-version` branch
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.37.0` |
| `@typescript-eslint/parser`            | `8.37.0` |
| `TypeScript`                           | `5.8.3` |
| `ESLint`                               | `9.31.0` |
| `node`                                 | `22.14.0` |

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11398 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Arcane regex tweaks to extract trailing path separators from the `tsconfigRootDir`.

### CODE REVIEW

File: packages/typescript-eslint/tests/getTsconfigRootDirFromStack.test.ts [hunk 1]
```diff
@@ -51,4 +51,35 @@ describe(getTSConfigRootDirFromStack, () => {
       expect(actual).toBe(expected);
     },
   );
+
+  it("doesn't get tricked by a messed up by not-an-eslint.config.js", () => {
```
Comment (JoshuaKGoldberg) [inline packages/typescript-eslint/tests/getTsconfigRootDirFromStack.test.ts]:
```suggestion
  it("doesn't get tricked by a not-an-eslint.config.js", () => {
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
⚡

**Comment by kirkwaiblinger** [comment]
Hang on — want to test a bit more

**Comment by JoshuaKGoldberg** [comment]
Merged into #11408.
