### ISSUE TITLE
ESLint 10: @typescript-eslint scope manager missing addGlobals (crash on flat config)

### ISSUE THREAD

**Issue by michaelgiraldo** [typescript-eslint/typescript-eslint#11829]
ESLint 10 crash: `scopeManager.addGlobals is not a function`

Env: ESLint 10.0.0-alpha.1 (`eslint@next`), @typescript-eslint/parser 8.49.0, @typescript-eslint/eslint-plugin 8.49.0, Node 20.19.0 (also repro on 25.2.1), flat config.

Repro:
npm init -y
npm i -D eslint@next @typescript-eslint/parser@8.49.0 @typescript-eslint/eslint-plugin@8.49.0 typescript globals
cat > eslint.config.js <<'EOFCONF'
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
export default [{
  files: ['**/*.ts'],
  languageOptions: { parser: tsParser, parserOptions: { project: false } },
  plugins: { '@typescript-eslint': tsPlugin },
  rules: { '@typescript-eslint/no-unused-vars': 'error' },
}];
EOFCONF
echo "const x: number = 1;" > index.ts
npx eslint index.ts --max-warnings=0

Actual: ESLint throws `TypeError: scopeManager.addGlobals is not a function` during SourceCode.finalize (before any rules run).
Expected: Lint completes or reports rule violations.
Regression: Works on ESLint 9.39.1 with the same config.

Request: ESLint 10 requires scope managers to implement addGlobals(names: string[]); please add this hook (or a compatibility shim) to the TS scope manager.
