### ISSUE TITLE
experimental-utils v3.0 requires TS 3.8 compiler and ES2015 target

### ISSUE THREAD

**Issue by adidahiya** [typescript-eslint/typescript-eslint#2114]
I just upgraded to typescript-eslint 3.0 in a TypeScript project which uses `@typescript-eslint/experimental-utils` and got a slightly surprising [compile error](https://app.circleci.com/pipelines/github/palantir/blueprint/166/workflows/6a310246-8687-4704-92a2-ab9d049dd428/jobs/32657/steps). The usage of ES private field syntax introduced in #2023 requires downstream TypeScript consumers to target ES2015 / ES6 or newer ([TS docs](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#ecmascript-private-fields)).

```
../../node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/RuleTester.d.ts:7:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
7     #private;
      ~~~~~~~~
```

This isn't a big problem for me, since I can update my `"target"` compiler option, but I just wanted to note this slight breaking change.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `3.0.1` |
| `TypeScript`                            | `3.9.3` |
| `node`                                  | `12.16.2` |

**Comment by bradzacher** [comment]
Interesting. I didn't realise that the truly private fields would even output in the `.d.ts` file.

there's no such thing as private field clashes, so it seems weird that they're even output in the `.d.ts`.

I was leveraging them because there was some stuff that I didn't want to leak, and I've made heavy use of them in the new scope manager #1939.

I'll update the release notes appropriately.

**Comment by Etheryte** [comment]
Ran into the same issue unexpectedly when adding experimental utils to an existing project. Downgrading to 2.34.0 worked out well for us for now because we can't upgrade TS on a whim.
