### PR TITLE
fix(typescript-estree): don't throw on missing tsconfig.json by default in project service

### LINKED ISSUE #9985: Bug: Upgrade to 8.5.0 breaks linting setup with NX and `projectService: true`
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

After upgrading `typescript-eslint` to the latest version `8.5.0` my linting setup with NX broke. 

The respective error message is `Parsing error: Could not read project service default project 'tsconfig.json': error TS5012: Cannot read file 'tsconfig.json': ENOENT: no such file or directory`. The respective files are included in a `tsconfig.lib.json` file which is being referenced from `tsconfig.json`. The same applies to files included by `tsconfig.spec.ts` (also referenced by `tsconfig.json`).

I am using `projectService: true` with a NX monorepo (see reproduction repo). The same setup worked fine with version `8.4.0`. The breaking change seems to be #9893.

### Reproduction Repository Link

https://github.com/hoi4/typescript-eslint-issue

### Repro Steps

1) clone the repo
2) `npm i`
3) `npx nx lint nx19 --skip-nx-cache`

Alternatively, when using `eslint` directly with an example file: `npx eslint apps/nx19/src/app/app.component.ts`

The latest commit uses version `8.5.0` which has the described issue. The previous commit holds a working state with version `8.4.0`. 

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.5.0` |
| `@typescript-eslint/parser`            | `8.5.0` |
| `@typescript-eslint/utils`             | `8.5.0` |
| `TypeScript`                           | `~5.5.2` |
| `ESLint`                               | `9.10.0` |
| `node`                                 | `20.15.0` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9985
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Changes error throwing to only occur if the user explicitly provides a `parserOptions.defaultProject`.

💖

### CODE REVIEW

**Review by auvred — APPROVED** [review]
:+1:

**Comment by ex0ns** [comment]
I have been troubleshooting this issue on my side without realizing there was an open issue/pr to already fix that. I was checking about the fix and wondering about the `if` inside the try, that involve knowing the subtle difference between the `config` and `optionRawObject`, it also feels a bit strange to parse the config file that might not exist and then wait for the exception.

I don't want to overstep, but I have tested the following solution (closer to what was done in 8.4)

```typescript
  if (options.allowDefaultProject?.length) {
    log('Enabling default project: %s', options.defaultProject);
    let configFile: ts.ParsedCommandLine;

    try {
      configFile = getParsedConfigFile(
        tsserver,
        options.defaultProject,
        tsconfigRootDir,
      );
    } catch (error) {
      throw new Error(
        `Could not read project service default project '${options.defaultProject}': ${(error as Error).message}`,
      );
    }

    service.setCompilerOptionsForInferredProjects(
      // NOTE: The inferred projects API is not intended for source files when a tsconfig
      // exists.  There is no API that generates an InferredProjectCompilerOptions suggesting
      // it is meant for hard coded options passed in. Hard asserting as a work around.
      // See https://github.com/microsoft/TypeScript/blob/27bcd4cb5a98bce46c9cdd749752703ead021a4b/src/server/protocol.ts#L1904
      configFile.options as ts.server.protocol.InferredProjectCompilerOptions,
    );
  }
```

Which will only try to parse the config if we actually want to use a defaultProject.

**Review by bradzacher — APPROVED** [review]
