### PR TITLE
feat: Support eslint@6

### LINKED ISSUE #564: [indent-new-do-not-use] Error with ESLint 6.0.0 pre-releases
**Repro**

```JSON
{
  "extends": "plugin:@typescript-eslint/eslint-recommended",
}
```

**Expected Result**

Able to parse and lint

**Actual Result**

Error: Failed to load plugin '@typescript-eslint': Cannot find module 'eslint/lib/util/ast-utils'

https://github.com/typescript-eslint/typescript-eslint/blob/cca1714c4bcb7a0349b4e10103870cc46bedf052/packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts#L11

**Additional Info**

```
Error: Failed to load plugin '@typescript-eslint' declared in '--config » ../../+typescript.js': Cannot find module 'eslint/lib/util/ast-utils'
Referenced from: /Users/teppei/src/github.com/teppeis/eslint-config-teppeis/+typescript.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/requireindex/index.js:52:28
    at Array.forEach (<anonymous>)
    at Object.module.exports [as default] (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/requireindex/index.js:34:11)
    at Object.<anonymous> (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/@typescript-eslint/eslint-plugin/dist/index.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConfigArrayFactory._loadPlugin (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:858:49)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:29)
    at ConfigArrayFactory._loadExtends (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:606:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:544:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:490:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:544:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:490:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:306:25)
    at ConfigArrayFactory.loadFile (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:381:16)
    at createCLIConfigArray (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:140:35)
    at new CascadingConfigArrayFactory (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:199:29)
    at new CLIEngine (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cli-engine.js:552:36)
    at verify (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/test/index.js:23:18)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser` | `1.9.0` |
| `TypeScript`                | `3.4.5` |
| `ESLint`                    | `6.0.0-alpha.2` |
| `node`                      | `10.15.3` |
| `npm`                       | `6.9.0` |

### LINKED ISSUE #644: Bump ESLint major version in Peer Dependencies (eslint 6.0)
**What code were you trying to parse?**

`npm install`

**What did you expect to happen?**

no warnings

**What actually happened?**

```
npm WARN @typescript-eslint/eslint-plugin@1.11.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.11.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | 1.11.0 |
| `TypeScript`                | latest |
| `ESLint`                    | `6.0.0` |
| `node`                      | `12.4.0` |
| `npm`                       | `6.9.0` |

### PR DESCRIPTION
**Pull request by bradzacher**
There was some weirdness around now requiring absolute paths for parser in test, but otherwise seemed to "just work"

BREAKING: dropped support for node 6

Fixes #644
Fixes #564

### CODE REVIEW

**Comment by bradzacher** [comment]
hmmmm this is going to be a breaking change technically, as we'll have to drop support for node v6 to run tests, unless we want to do some funky stuff with tests...

**Comment by platinumazure** [comment]
For what it's worth, Node 6 is fully unsupported/end-of-life even by the Node team at this point.

**Comment by jhpratt** [comment]
Given the only tests failing are on Node 6, this looks good to me. I'm currently unable to use typescript-eslint on a new project, and I'd prefer to not have to downgrade my eslint version temporarily.

**Comment by bradzacher** [comment]
@jhpratt why can't you use it in your project? You should only get warnings about peer deps not matching up. If you look at the changes in this PR - they are all either types or tests - the plugin works fine on 6.0.0 as is. That is, unless you're using a tool like yarnpnp or something that makes things hard fail if you don't use the right versions.

---

It's not as simple as just merging this and releasing a minor bump.
We will have to remove support for node 6. This is (obviously) backwards incompatible, meaning a major version bump.
I have no problem doing that, however there is a bunch of things we wanted to do with our next major version bump (#501). So we need to step back and coordinate to get all of our breaking changes done together, so we can release 2.0.0 and not have to worry about releasing 3.0.0 shortly after.

Ultimately 6.0.0 came out ~5 days ago, so there's no great rush to get this in.

**Comment by jhpratt** [comment]
@bradzacher I get the following error when trying to lint

```
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.yaml': Cannot find module 'eslint/lib/util/traverser'
Require stack:
- ./node_modules/@typescript-eslint/parser/dist/parser.js
- ./node_modules/eslint/lib/cli-engine/config-array-factory.js
- ./node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- ./node_modules/eslint/lib/cli-engine/cli-engine.js
- ./node_modules/eslint/lib/cli-engine/index.js
- ./node_modules/eslint/lib/cli.js
- ./node_modules/eslint/bin/eslint.js
```

I'm using `@typescript-eslint/parser@^1.10.2` and `eslint@^6.0.0`.

**Comment by bradzacher** [comment]
Switch to the latest version of the parser, which is `1.11.0`, and which contains a fix for that bug (released 3 days ago)....

**Comment by jhpratt** [comment]
Not sure how I missed that. Works as expected — thanks!

**Comment by trivikr** [comment]
@bradzacher Does this mean eslint@v6 will be supported and support for Node.js v6 will be dropped in typescript-eslint@v2.x?
> I have no problem doing that, however there is a bunch of things we wanted to do with our next major version bump (#501). So we need to step back and coordinate to get all of our breaking changes done together, so we can release 2.0.0 and not have to worry about releasing 3.0.0 shortly after.

**Comment by bradzacher** [comment]
@trivikr - correct. ESLint@6 is implicitly supported by `v1.11.0` of our stuff, but yarn/npm will log a warning due to incorrect peer dep ranges..

This PR will be part of `v2.0.0` of this project. Specifically this PR will drop explicit support for Node.js@6, and add explicit support for ESLint@6.
