### PR TITLE
fix(experimental-utils): downlevel type declarations for versions older than 3.8

### LINKED ISSUE #2114: experimental-utils v3.0 requires TS 3.8 compiler and ES2015 target
I just upgraded to typescript-eslint 3.0 in a TypeScript project which uses `@typescript-eslint/experimental-utils` and got a slightly surprising [compile error](https://app.circleci.com/pipelines/github/palantir/blueprint/166/workflows/6a310246-8687-4704-92a2-ab9d049dd428/jobs/32657/steps). The usage of ES private field syntax introduced in #2023 requires downstream TypeScript consumers to target ES2015 / ES6 or newer ([TS docs](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#ecmascript-private-fields)).

```
../../node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/RuleTester.d.ts:7:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
7     #private;
      ~~~~~~~~
```

This isn't a big problem for me, since I can update my `"target"` compiler option, but I just wanted to note this slight breaking change.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `3.0.1` |
| `TypeScript`                            | `3.9.3` |
| `node`                                  | `12.16.2` |

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #2114

Use `downlevel-dts` to do it.
I thought about just removing the private fields, but I think this is better for ensuring we don't cause regressions going forward.

Also it sets a precedence that I will leverage as part of #1939.

### CODE REVIEW

**Comment by adidahiya** [comment]
TIL about `downlevel-dts`. neat!
