### ISSUE TITLE
scope.resolve is not a function

### ISSUE THREAD

**Issue by ertrzyiks** [typescript-eslint/typescript-eslint#2596]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

1. Install the typescript linter and [Cypress plugin](https://github.com/cypress-io/eslint-plugin-cypress)
```
"@typescript-eslint/eslint-plugin": "^4.2.0",
"@typescript-eslint/parser": "^4.2.0",
"eslint-plugin-cypress": "^2.11.1",
```
2. Use code that requires `scope.resolve` method, in case of cypress plugin it must be a `cy.wait` call with identifier.
```ts
const i = 100
cy.wait(i)
```
3. See the linter crash

I put together this in the example repo: https://github.com/ertrzyiks/typescript-eslint-cypress-conflict

```JSON
{
    "plugins": [
        "@typescript-eslint",
        "cypress"
    ],
    "rules": {
        "cypress/no-unnecessary-waiting": "error"
    }
}
```

**Expected Result**

scope.resolve is a function as it is defined in `eslint-scope`, the linter rule can process the code

**Actual Result**

Eslint crashes with

> Oops! Something went wrong! :(
> TypeError: scope.resolve is not a function

**Additional Info**
We noticed this error after migrating from `@typescript-eslint/parser` 2.x to 4.x. From what I see it worked on 2.x because the `eslint-scope `was expanded and now it's reimplemented without `resolve` method.

I skip the debug log as it can be inspected in the example repo.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.2.0` |
| `TypeScript`                | `4.0.3` |
| `ESLint`                    | `7.9.0` |
| `node`                      | `12.16.1` |

**Comment by bradzacher** [comment]
https://github.com/cypress-io/eslint-plugin-cypress/blob/master/lib/rules/no-unnecessary-waiting.js#L59

They are using a _deprecated_ API
https://eslint.org/docs/developer-guide/scope-manager-interface#deprecated-members-2

I purposely opted not to implement deprecated members to save time and effort.

Should be a simple fix for them to upgrade to non-deprecated APIs. This will also future proof them.

Please file an issue with them.

**Comment by ertrzyiks** [comment]
@bradleyayers makes sense, thanks for the quick answer 👍
