### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-conversion] only report ~~ on integer literal types

### LINKED ISSUE #11491: Bug: [no-unnecessary-type-conversion] Unsafe suggestion: removing bitwise `~~` changes semantics for non-integer numbers
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.9.2&fileType=.tsx&code=MYewdgzgLgBAhjAvDAjABgHQoLACg%2BiSwBGSMAfuXHgPQ0wMwB6qaQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWmQ5MAbomjJKM9FAXQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const a = 1.1
const b = ~~a
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-type-conversion": "error"
  }
};
```

### tsconfig

```jsonc

```

### Expected Result

No suggestion for `~~` case

### Actual Result

The rule reports:
> Using ~~ on a number does not change the type or value of the number.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mouse0429**
## PR Checklist

- [X] Addresses an existing open issue: fixes #11491
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Modified the rule to only report ~~ as unnecessary when applied to integer literal types:
* ~~5 → Reports as unnecessary ✅ (literal integer)
* ~~(3 | 4) → Reports as unnecessary ✅ (union of integer literals)
* ~~1.1 → No report ✅ (decimal literal - meaningful conversion)
* ~~(2 + 2) → No report ✅ (expression - conservative approach)

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 thanks!

**Review by kirkwaiblinger — APPROVED** [review]
🎉🎉

**Comment by JoshuaKGoldberg** [comment]
Hmm, CI has some odd failures after merging from `main`. 

```plaintext
packages/type-utils/src/TypeOrValueSpecifier.ts(2,34): error TS7016: Could not find a declaration file for module '@typescript-eslint/utils/json-schema'. '/home/runner/work/typescript-eslint/typescript-eslint/packages/utils/dist/json-schema.js' implicitly has an 'any' type.
...
```

They shouldn't be related to this PR. They don't happen locally for me. FYI @JamesHenry
